#!/bin/bash
#s This script is under license BEER-WARE.
# "THE BEER-WARE LICENSE" (Revision 42):
# <eric@obarun.org> wrote this file.  As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return.   Eric Vidal

# functions file for obarun-build package

shopt -s extglob

source /usr/lib/obarun/common_functions
source /etc/obarun/build.conf

templates="${templates:-/usr/share/obarun/obarun-build/templates}"
workdir="build_pkg"
workconf="build_conf"

clean_install(){
	echo_bold "clean install"
}

usage(){
	echo_bold "usage"
}

create(){
	
	local file
	local -a file_list
	mapfile -t file_list < <(ls --group-directories-first ${templates}/*)

	# check if templates directory exist on $target
	# create it if doesn't exist
	check_dir "${target}/${named}/${workconf}"
	if (( $? )); then
		echo_display " Create ${target}/${named}/${workconf}"
		mkdir -p "${target}/${named}/${workconf}" || die " Impossible to create directory ${target}/${named}/${workconf}" 
	fi
	# check if configuration templates exist
	# if not create it
	for file in "${file_list[@]}"; do
		file=${file##*/}
		search_in_dir "${target}/${named}" "${workconf}" "${file}"
		if (( $? )); then
			echo_display " Copy ${file} templates file to ${target}/${named}/${workconf}"
			cp "${templates}/${file}" "${target}/${named}/${workconf}" || die " Impossible to copy ${file}"
		fi
	done
	
	cont_create(){
		export named="${named}"
		export workdir="${workdir}"
		export workconf="${workconf}"
		export cont_create_conf="${target}/${named}/${workconf}/cont_create.conf"
		lxc-create -n "${named}" -t "${target}/${named}/${workconf}/cont_create" || die " Impossible to create the container"
	}
	cont_create
}

build(){
	echo_bold "build"
}

start(){
	echo_bold "start"
}
