#!@BINDIR@/bash
# Copyright (c) 2015-2017 Eric Vidal <eric@obarun.org>
# All rights reserved.
# 
# This file is part of Obarun. It is subject to the license terms in
# the LICENSE file found in the top-level directory of this
# distribution and at https://github.com/Obarun/obarun-build/LICENSE
# This file may not be copied, modified, propagated, or distributed
# except according to the terms contained in the LICENSE file.
#
# template script for generating Obarun container with lxc

# functions file for obarun-build package

sourcing(){
	
	local list
	
	for list in /etc/obarun/build.conf /usr/lib/obarun/{util.sh,build.sh} /usr/lib/obarun/build/*; do
		if [[ -f "${list}" ]]; then
			source "${list}"
		else
			out_error "Missing file : ${list}"
			exit	
		fi
	done
	
	unset list
}
sourcing

ARCH="x86_64"
CONT_ROOTFS="${TARGET}/${named}/${WORKDIR}/rootfs"
PAC_CONF="/etc/pacman.conf"
MAKEPKG_CONF="/etc/makepkg.conf"
START_CONF="${TARGET}/${named}/${WORKCONF}/start.conf"

shellopts_save
shellopts_set_unset "extglob" 0

# Detect use under userns (unsupported)
for arg in "$@"; do
    [ "$arg" = "--" ] && break
    if [ "$arg" = "--mapped-uid" -o "$arg" = "--mapped-gid" ]; then
        out_error "This template can't be used for unprivileged containers." 1>&2
        exit 1
    fi
done

# Make sure the usual locations are in PATH
export PATH=$PATH:/usr/local/bin:/usr/bin:/sbin:/bin

# Ensure strict root's umask doesn't render the VM unusable
umask 022

create_dir(){
	
	out_action "Create needed directory in ${CONT_ROOTFS}"
	mkdir -m 0755 -p "${CONT_ROOTFS}"/var/{cache/pacman/pkg,lib/pacman,lib/pacman/sync,log} "${CONT_ROOTFS}"/{dev,run,etc,etc/pacman.d}
	mkdir -m 0755 -p "${CONT_ROOTFS}"/dev/{pts,shm}
	mkdir -m 1777 -p "${CONT_ROOTFS}"/tmp
	mkdir -m 0555 -p "${CONT_ROOTFS}"/{sys,proc}
	
	return 0
}

pac_file(){
	
	if [[ -d /etc/pacman.d/gnupg && ! -d $CONT_ROOTFS/etc/pacman.d/gnupg ]]; then
		out_action "Copying gnupg directory"
		cp -a /etc/pacman.d/gnupg "${CONT_ROOTFS}/etc/pacman.d/" || die " Impossible to copy gnupg directory" 
	fi
	
	out_action "Copying mirrorlist"
	cp -af /etc/pacman.d/mirrorlist "${CONT_ROOTFS}/etc/pacman.d/" || die " Impossible to copy mirrorlist list" 
	
	out_action "Copying pacman database"
	cp -f "/var/lib/pacman/sync/"*.* "${CONT_ROOTFS}/var/lib/pacman/sync/" || die " Impossible to copy pacman database" 
	
	return 0 
}

# install packages within container 
install_cont() {
	create_dir
	pac_file
	mount_umount "${CONT_ROOTFS}" "mount" || die " Failed to mount ${CONT_ROOTFS}"
	
	# install base first
	pacman -r "${CONT_ROOTFS}" -S $(grep -h -v ^# $TARGET/$named/$WORKCONF/pkglist_base) --noconfirm --config "${PAC_CONF}" --gpgdir "${GPG_DIR}" || die " Impossible to install packages" 
	
	# install package
    pacman -r "${CONT_ROOTFS}" -S $(grep -h -v ^# $TARGET/$named/$WORKCONF/pkglist_{boot,devel,extra}) --noconfirm --config "${PAC_CONF}" --gpgdir "${GPG_DIR}" || die " Impossible to install packages" 
	
	# pacman installation push mirrorlist to .pacsave,
	# so copy again to erase the change
	out_action "Copying mirrorlist"
	cp -af /etc/pacman.d/mirrorlist "${CONT_ROOTFS}/etc/pacman.d/" || die " Impossible to copy mirrorlist list" 
	
    return 0
}

# customize container
customize_cont() {
	
	out_action "Copying locale file at ${CONT_ROOTFS}/etc/"  
    cp -fp /etc/locale.conf /etc/locale.gen "${CONT_ROOTFS}/etc/" || die  " Impossible to copy locale file" 
	
	out_action "Copy pacman.conf in ${CONT_ROOTFS}"
	cp -f "${PAC_CONF}" "${CONT_ROOTFS}"/etc || die  " Impossible to copy the file ${PAC_CONF}" 
	
	out_action "Copy makepkg.conf in ${CONT_ROOTFS}"
	cp -f "${MAKEPKG_CONF}" "${CONT_ROOTFS}"/etc || die  " Impossible to copy the file ${MAKEPKG_CONF}" 
	
	config_hostname
	
	config_locale
	
	config_localetime
	
	config_keymap
	
	config_user
	
	config_root
	
	add_at_logroup
	
	config_console
	
	config_resolv
	
	return 0
}

config_hostname(){
	
	out_action "Define hostname as : ${HOSTNAME}"
	if [[ -n "$HOSTNAME" ]]; then
		sed -i 's/ .*$//' "${CONT_ROOTFS}/etc/hosts" || die  " Impossible to define hosts" 
	fi

	sed -i "s/HOSTNAME=.*$/HOSTNAME=$HOSTNAME/g" "${CONT_ROOTFS}/etc/s6/s6.conf" || die  " Impossible to define hostname on s6.conf" 
	
	echo "$HOSTNAME" > "${CONT_ROOTFS}/etc/hostname" || die " Impossible to define hostname"
	sed -i '/127.0.0.1/s/$/ '$HOSTNAME'/' "${CONT_ROOTFS}/etc/hosts" || die  " Impossible to define hosts" 
	sed -i '/::1/s/$/ '$HOSTNAME'/' "${CONT_ROOTFS}/etc/hosts" || die  " Impossible to define hosts" 
	
	out_valid "hostname was configured successfully"
	
}
config_locale(){
	
	out_action "Define locale"
	chroot "${CONT_ROOTFS}" locale-gen || die  " Impossible to launch locale-gen" 
	echo LANG="$LOCALE" > "${CONT_ROOTFS}/etc/locale.conf" || die  " Impossible to define locale.conf" 
    echo LC_COLLATE=C >> "${CONT_ROOTFS}/etc/locale.conf" || die  " Impossible to define locale.conf" 
	
	out_valid "Locale was created successfully"
	
}
config_localetime(){
	
	out_action "Define localtime"
	if [[ "$SUBZONE" != "" ]]; then
		sed -i "s/TZ=.*$/TZ=$ZONE\/$SUBZONE/g" "${CONT_ROOTFS}/etc/s6/s6.conf" || die  " Impossible to define localtime on s6.conf" 
	else
		sed -i "s/TZ=.*$/TZ=$ZONE/g" "${CONT_ROOTFS}/etc/s6/s6.conf" || die  " Impossible to define localtime on s6.conf" 
	fi
	
	out_valid "Localetime was configured successfully"
	
}
config_keymap(){
	
	out_action "Define keymap" 
	sed -i "s,KEYMAP=.*$,KEYMAP=${KEYMAP},g" "${CONT_ROOTFS}/etc/s6/s6.conf" || die  " Impossible to set ${KEYMAP} on s6.conf" 
		
	out_valid "Console keymap was configured successfully"
	
}
config_user(){
	
	out_action "Define ${NEWUSER}"
	
	chroot "${CONT_ROOTFS}" useradd -m -g users -G "wheel,disk,storage,optical,floppy,network" -s /bin/bash "${NEWUSER}" || die  " Failed to create ${NEWUSER}" 
	
	echo "${NEWUSER}:${PASSW_USER}" | chroot "${CONT_ROOTFS}" chpasswd || die  " Failed to change ${NEWUSER} password" 
	
	out_valid "User ${NEWUSER} was created successfully" 
	
}
config_root(){
	
	out_action "Define root"

	echo "root:${PASSW_ROOT}" | chroot "${CONT_ROOTFS}" chpasswd || die  " Failed to change root password" 
	
	out_valid "root user was configured successfully" 
	
}
add_at_logroup(){
	
	out_action "add ${NEWUSER} at log group"
	
	chroot "${CONT_ROOTFS}" gpasswd -a "${NEWUSER}" log || die  " Impossible to add user ${NEWUSER} at log group" 
}
config_console(){

	# enable getty on active ttys
    local nttys=$(grep "^lxc.tty.max" "${START_CONF}"| head -n1 | cut -d= -f2 | tr -d "[:blank:]")
    local devttydir=$(grep "^lxc.tty.dir" "${START_CONF}" | head -n1 | cut -d= -f2 | tr -d "[:blank:]")
      
    # bind getty instances to /dev/<devttydir>/tty* if lxc.devttydir is set
    if [[ -n "${devttydir}" ]]; then
		echo "${devttydir}/console" >> "${CONT_ROOTFS}/etc/securetty" || die  " Impossible to set ${devttydir}/console in ${CONT_ROOTFS}/etc/securetty" 
		# update securetty to allow console login if devttydir is set
		for i in $(seq 1 ${nttys:-1}); do
            echo "${devttydir}/tty${i}" >> "${CONT_ROOTFS}/etc/securetty" || die  " Impossible to set ${devttydir}/tty${i} in ${CONT_ROOTFS}/etc/securetty" 
        done
	fi
   	
	# optional here, do not die if an error is created
	echo "# For libvirt/Virtual Machine Monitor" >> ${CONT_ROOTFS}/etc/securetty
    echo "pts/0" >> ${CONT_ROOTFS}/etc/securetty
    
    return 0
}
# Write container configuration files
config_container_file() {

	local config="${LXC_CONF}/${named}/config" LXC_NETWORK_HWADDR=00:16:3e:$(openssl rand -hex 3| sed 's/\(..\)/\1:/g; s/.$//')
   
    rm -f ${config}
   
    echo "lxc.uts.name = ${named}" >> "${config}" || die  " Impossible to config lxc.uts.name at ${config}" 
	echo "lxc.arch = ${ARCH}" >> "${config}" || die  " Impossible to config lxc.arch at ${config}" 
	echo "lxc.rootfs.path = ${CONT_ROOTFS}" >> "${config}" || die  " Impossible to config lxc.rootfs.path at ${config}" 
    if [ -e "${START_CONF}" ]; then 
        echo "lxc.include = ${START_CONF}" >> "${config}" || die  " Impossible to config lxc.include at ${config}" 
    fi
    if (( ${CREATE_BRIDGE} ));then
		echo "lxc.net.0.type = veth" >> "${config}" || die  " Impossible to config lxc.net.0.type at ${config}" 
		echo "lxc.net.0.link = lxcbr0" >> "${config}" || die  " Impossible to config lxc.net.0.link at ${config}" 
		echo "lxc.net.0.flags = up" >> "${config}" || die  " Impossible to config lxc.net.0.flags at ${config}" 
		echo "lxc.net.0.ipv4.address = 10.0.3.$((RANDOM%253))/24" >> "${config}" || die  " Impossible to config lxc.net.0.ipv4.address at ${config}" 
		echo "lxc.net.0.ipv4.gateway = 10.0.3.1" >> "${config}" || die  " Impossible to config lxc.net.0.ipv4.gateway at ${config}"
		echo "lxc.net.0.hwaddr = ${LXC_NETWORK_HWADDR}" >> "${config}" || die  " Impossible to config lxc.net.0.hwaddr at ${config}" 
		echo "lxc.net.0.name = eth0" >> "${config}" || die  " Impossible to config lxc.net.0.name at ${config}" 
		/usr/lib/lxc/lxc-net start
    fi
    
	return 0
	
}

config_resolv() {
	out_action "Confing resolv.conf in ${CONT_ROOTFS} with 8.8.8.8 as nameserver"
	echo "nameserver 8.8.8.8" > "${CONT_ROOTFS}/etc/resolv.conf" || die  " Impossible to copy the file resolv.conf" 
}

mkdir -p "${CONT_ROOTFS}"

install_cont

customize_cont

config_container_file

out_valid "The configuration file is stored at ${TARGET}/${named}/${WORKCONF}."


